import type { Metadata } from "next";
import StyledComponentsRegistry from "../registry";
import "@/styles/globals.css";
import ClientOnly from "@/components/ClientOnly";

import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";
import { AuthProvider } from "@/context/AuthContext";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function AuthLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClientOnly>
      <AuthProvider>
        <StyledComponentsRegistry>
          {children}
          <ToastContainer />
        </StyledComponentsRegistry>
      </AuthProvider>
    </ClientOnly>
  );
}
