import type { Metadata } from "next";
import StyledComponentsRegistry from "../registry";
import "@/styles/globals.css";

import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";
import { AuthProvider } from "@/context/AuthContext";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <AuthProvider>
          <StyledComponentsRegistry>
            {children}
            <ToastContainer />
          </StyledComponentsRegistry>
        </AuthProvider>
      </body>
    </html>
  );
}
